title: Jeff Disbrow # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Interests:<br>
  -Remote Sensing<br>
  -Geospatial Analysis<br>
  -Open-source Developmetn<br>
  -Landscape Change<br>
  -Machine Learning / Deep Learning <br>
  <br><br>
  Skills:<br>
  -ArcGIS Suite<br>
  -QGIS <br>
  -eCognition <br>
  -LAStools <br>
  -GlobalMapper <br>
  -Pix4D (Photogrammetry)<br>
  -Unmanned Aerial Systems (UAS) <br>

  
theme: jekyll-theme-minima
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
