title: Jeff Disbrow 
logo: "/images/logo.png?raw=true" 
description: >
  Interests:<br>
  -Remote Sensing<br>
  -Open-source Developmetn<br>
  -Machine Learning / Deep Learning <br>
  -Landscape Change<br>
  <br>
  Skills:<br>
  -ArcGIS Suite<br>
  -QGIS <br>
  -eCognition <br>
  -LAStools <br>
  -GlobalMapper <br>
  -Pix4D (Photogrammetry)<br>
  -Unmanned Aerial Systems (UAS) <br>

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
